// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

func test_hover_test027(): unit {
    /**
    *test hover
    *test_hover_test027_in
    */
    func test_hover_test027_in():int32 {
        return 1
    }
    var value :int32  = test_hover_test027_in()
}
