// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

import testpkgerror.*

class documentHighlight_test058 <: iPkg {
    func foo() :int32{
        return 1
    }

    var a = iPkg.getSum58()
    var b = iPkg.getSum58()
}
