// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package default.pkg_alias01

public var var02 = 2

public func func02() {
    return 3
}

public func func02(a:Int32) {
    return 3
}


public func func02(a:Int32,b:Int32) {
    return 3
}

