// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package default.pkgA
public var varC = 1
public let letC = 1
public class classC{func classTest(){}}
public enum enumC{|d|a|y}
public struct structC{}
public interface interfaceC{}
public func A1(){}
let cccc= 11
