// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

import default.package1.*

public var dir1_a = 1

public class dir1_c {
    public var a1 = pkg1_c1()
    public func test1() {}
}

main() {
    print("Hello World!")
}

