// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package pkg01_reference
class test001_fn01{
    static var  def_var01 = "test001"
    public static func def_func_test001(){
        var aaa = def_var01
        return aaa
    }
}

