// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package E

import A.*

@M1
func test() {
    var abc123 = 10
    var abc456 = 20
    abc
}

@M3
func test() {
    var abc123 = 10
    var abc456 = 20
    abc
}
