// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package demo
import demo.a.*

public enum TimeUnita {
    zzzzzzzzzz(Int64)
}

main() {
    let time = TimeUnit.zzzzzzzz(1)
    let h = match (time) {
        case zzzzz => 1
        case _ => 2
    }
}















