// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package classExtend
public enum B {
    |D|M|Y
}
public class  A{
    func foo(){}
}
extend A{
   func Extendfoo( )  {

    }
}
let c = A().
