// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package vscode_cangjie

func testDeprecated() {
    var alias: AssociatedTypeT = 0
    testcc("s: String", 
    "ss: String", b: 1)
    var clazz: Claz
    C.
}
