// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package b.b

import b.a.*
public interface blackPeople <: People{

}
public open class student <: xzf & People {
    public static var name: String = "aaaa";
    public static func studentage() {
        xzfage()
    }
}
 public struct IT <:love{
     public static var name: String = "aaaa";
 }


