// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package ohos_app_cangjie_entry.test12.test12_b
import ohos_app_cangjie_entry.test12.Test12

func test12_b() {
   var test12_t = Test12()
    test12_t  //test
}
