// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

func semanticHighlight_test022():unit {
    var a:String = "not a valid score"
    var b:String = """not a valid score
    not a valid score
    not a valid score
    not a valid "score"
    """
}
