// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package testpkg01
import testpkg.*

func semanticHighlight_test005(){
    var a:int32 = testpkg.one
    var b:int32 = testpkg.testpkgFunc()

}
