// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package default.Func.pkg2
public import default.Func.pkg1.pkg1_class as ccccccc

public open class pkg2_class{
    init(a: Int64) {
        
    }
}
let aaa = cccccc


