// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package default.pkgB.aaaa
public enum aaaa{
    enumA|enumB|enumFunc(Int64,Float16)
    func enumCC(a:Int32,b!:String,c!:Int64=1) {
        1
    }
} 
