// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

//1
public class RR{
   private func a(){}
   protected func b(){}
}

func f30(){
    var y = RR().a()
}
//2
public func asanGC() {
    gjgjghj(4.6)
}


func gjgjghj(a:Int64){}
